/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *Gerer_les_factures;
  GtkWidget *Voit;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  Gerer_les_factures = gtk_button_new_with_mnemonic (_("Gerer les factures"));
  gtk_widget_show (Gerer_les_factures);
  gtk_fixed_put (GTK_FIXED (fixed1), Gerer_les_factures, 64, 40);
  gtk_widget_set_size_request (Gerer_les_factures, 224, 53);
  gtk_container_set_border_width (GTK_CONTAINER (Gerer_les_factures), 3);

  Voit = gtk_button_new_with_mnemonic (_("Voitures"));
  gtk_widget_show (Voit);
  gtk_fixed_put (GTK_FIXED (fixed1), Voit, 72, 144);
  gtk_widget_set_size_request (Voit, 216, 56);

  g_signal_connect ((gpointer) Gerer_les_factures, "clicked",
                    G_CALLBACK (on_Gerer_les_factures_clicked),
                    NULL);
  g_signal_connect ((gpointer) Voit, "clicked",
                    G_CALLBACK (on_Voit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, Gerer_les_factures, "Gerer_les_factures");
  GLADE_HOOKUP_OBJECT (window1, Voit, "Voit");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *eventbox1;
  GtkWidget *fixed2;
  GtkWidget *entry2CIN;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview2;
  GtkWidget *recherche;
  GtkWidget *ajout_fact;
  GtkWidget *button11;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label51;
  GtkWidget *mod;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label60;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (window2), eventbox1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (eventbox1), fixed2);

  entry2CIN = gtk_entry_new ();
  gtk_widget_show (entry2CIN);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2CIN, 192, 24);
  gtk_widget_set_size_request (entry2CIN, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry2CIN), _("CIN"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2CIN), 8226);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow1, 104, 72);
  gtk_widget_set_size_request (scrolledwindow1, 328, 216);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview2);
  gtk_widget_set_size_request (treeview2, 300, 200);

  recherche = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (recherche);
  gtk_fixed_put (GTK_FIXED (fixed2), recherche, 352, 24);
  gtk_widget_set_size_request (recherche, 74, 29);

  ajout_fact = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (ajout_fact);
  gtk_fixed_put (GTK_FIXED (fixed2), ajout_fact, 272, 296);
  gtk_widget_set_size_request (ajout_fact, 106, 37);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed2), button11, 160, 296);
  gtk_widget_set_size_request (button11, 96, 37);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button11), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox6), label51, FALSE, FALSE, 0);

  mod = gtk_button_new ();
  gtk_widget_show (mod);
  gtk_fixed_put (GTK_FIXED (fixed2), mod, 56, 296);
  gtk_widget_set_size_request (mod, 82, 37);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (mod), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox7), label60, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) recherche, "clicked",
                    G_CALLBACK (on_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_fact, "clicked",
                    G_CALLBACK (on_ajout_fact_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) mod, "clicked",
                    G_CALLBACK (on_mod_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, entry2CIN, "entry2CIN");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window2, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window2, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (window2, ajout_fact, "ajout_fact");
  GLADE_HOOKUP_OBJECT (window2, button11, "button11");
  GLADE_HOOKUP_OBJECT (window2, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window2, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window2, image6, "image6");
  GLADE_HOOKUP_OBJECT (window2, label51, "label51");
  GLADE_HOOKUP_OBJECT (window2, mod, "mod");
  GLADE_HOOKUP_OBJECT (window2, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window2, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window2, image7, "image7");
  GLADE_HOOKUP_OBJECT (window2, label60, "label60");

  return window2;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed4;
  GtkWidget *entry6;
  GtkWidget *label16;
  GtkWidget *label36;
  GtkWidget *label35;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label34;
  GtkWidget *label10;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label12;
  GtkWidget *label33;
  GtkWidget *label11;
  GtkWidget *label37;
  GtkWidget *entry12;
  GtkWidget *valider;
  GtkWidget *valid;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4), fixed4);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 288, 312);
  gtk_widget_set_size_request (entry6, 72, 27);
  gtk_entry_set_text (GTK_ENTRY (entry6), _("%100"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  label16 = gtk_label_new (_("*Pourcentage de reduction:"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 88, 312);
  gtk_widget_set_size_request (label16, 192, 25);

  label36 = gtk_label_new ("");
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed4), label36, 200, 272);
  gtk_widget_set_size_request (label36, 104, 16);

  label35 = gtk_label_new ("");
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 208, 248);
  gtk_widget_set_size_request (label35, 152, 16);

  label13 = gtk_label_new (_("Date de naissance: "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 32, 224);
  gtk_widget_set_size_request (label13, 96, 17);

  label14 = gtk_label_new (_("*Type de reservation:"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 16, 248);
  gtk_widget_set_size_request (label14, 168, 16);

  label15 = gtk_label_new (_("*Date:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 8, 272);
  gtk_widget_set_size_request (label15, 80, 16);

  label34 = gtk_label_new ("");
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 176, 224);
  gtk_widget_set_size_request (label34, 80, 17);

  label10 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed4), label10, 8, 128);
  gtk_widget_set_size_request (label10, 96, 16);

  label30 = gtk_label_new (_("123"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 96, 128);
  gtk_widget_set_size_request (label30, 104, 16);

  label31 = gtk_label_new (_("Prenom:"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed4), label31, 16, 152);
  gtk_widget_set_size_request (label31, 89, 16);

  label32 = gtk_label_new ("");
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 136, 152);
  gtk_widget_set_size_request (label32, 73, 16);

  label12 = gtk_label_new (_("CIN: "));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 8, 176);
  gtk_widget_set_size_request (label12, 80, 16);

  label33 = gtk_label_new ("");
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 88, 176);
  gtk_widget_set_size_request (label33, 88, 16);

  label11 = gtk_label_new (_("Tel: "));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed4), label11, 16, 200);
  gtk_widget_set_size_request (label11, 64, 16);

  label37 = gtk_label_new ("");
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 88, 200);
  gtk_widget_set_size_request (label37, 89, 16);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed4), entry12, 72, 40);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry12), _("CIN"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  valider = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed4), valider, 264, 40);
  gtk_widget_set_size_request (valider, 74, 29);

  valid = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (valid);
  gtk_fixed_put (GTK_FIXED (fixed4), valid, 336, 360);
  gtk_widget_set_size_request (valid, 106, 29);

  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) valid, "clicked",
                    G_CALLBACK (on_valid_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window4, label16, "label16");
  GLADE_HOOKUP_OBJECT (window4, label36, "label36");
  GLADE_HOOKUP_OBJECT (window4, label35, "label35");
  GLADE_HOOKUP_OBJECT (window4, label13, "label13");
  GLADE_HOOKUP_OBJECT (window4, label14, "label14");
  GLADE_HOOKUP_OBJECT (window4, label15, "label15");
  GLADE_HOOKUP_OBJECT (window4, label34, "label34");
  GLADE_HOOKUP_OBJECT (window4, label10, "label10");
  GLADE_HOOKUP_OBJECT (window4, label30, "label30");
  GLADE_HOOKUP_OBJECT (window4, label31, "label31");
  GLADE_HOOKUP_OBJECT (window4, label32, "label32");
  GLADE_HOOKUP_OBJECT (window4, label12, "label12");
  GLADE_HOOKUP_OBJECT (window4, label33, "label33");
  GLADE_HOOKUP_OBJECT (window4, label11, "label11");
  GLADE_HOOKUP_OBJECT (window4, label37, "label37");
  GLADE_HOOKUP_OBJECT (window4, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (window4, valider, "valider");
  GLADE_HOOKUP_OBJECT (window4, valid, "valid");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed5;
  GtkWidget *button7;
  GtkWidget *prix;
  GtkWidget *label59;
  GtkWidget *date_retour;
  GtkWidget *label22;
  GtkWidget *datealler;
  GtkWidget *label21;
  GtkWidget *typereservation;
  GtkWidget *date;
  GtkWidget *label20;
  GtkWidget *label18;
  GtkWidget *label53;
  GtkWidget *label17;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkWidget *label19;
  GtkWidget *tel;
  GtkWidget *cin;
  GtkWidget *label23;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);

  button7 = gtk_button_new_with_mnemonic (_("Imprimer"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 264, 328);
  gtk_widget_set_size_request (button7, 160, 24);

  prix = gtk_label_new ("");
  gtk_widget_show (prix);
  gtk_fixed_put (GTK_FIXED (fixed5), prix, 200, 272);
  gtk_widget_set_size_request (prix, 49, 17);

  label59 = gtk_label_new (_("Date retour :"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed5), label59, 24, 224);
  gtk_widget_set_size_request (label59, 177, 17);

  date_retour = gtk_label_new ("");
  gtk_widget_show (date_retour);
  gtk_fixed_put (GTK_FIXED (fixed5), date_retour, 176, 208);
  gtk_widget_set_size_request (date_retour, 105, 17);

  label22 = gtk_label_new (_("Date Aller :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 40, 200);
  gtk_widget_set_size_request (label22, 136, 17);

  datealler = gtk_label_new ("");
  gtk_widget_show (datealler);
  gtk_fixed_put (GTK_FIXED (fixed5), datealler, 224, 232);
  gtk_widget_set_size_request (datealler, 104, 17);

  label21 = gtk_label_new (_("Type de reservation:"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed5), label21, 40, 168);
  gtk_widget_set_size_request (label21, 144, 17);

  typereservation = gtk_label_new ("");
  gtk_widget_show (typereservation);
  gtk_fixed_put (GTK_FIXED (fixed5), typereservation, 192, 168);
  gtk_widget_set_size_request (typereservation, 104, 17);

  date = gtk_label_new ("");
  gtk_widget_show (date);
  gtk_fixed_put (GTK_FIXED (fixed5), date, 136, 136);
  gtk_widget_set_size_request (date, 88, 16);

  label20 = gtk_label_new (_("Date:"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 32, 136);
  gtk_widget_set_size_request (label20, 65, 17);

  label18 = gtk_label_new (_("Tel:"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed5), label18, 8, 112);
  gtk_widget_set_size_request (label18, 96, 16);

  label53 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed5), label53, 40, 64);
  gtk_widget_set_size_request (label53, 72, 16);

  label17 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed5), label17, 0, 40);
  gtk_widget_set_size_request (label17, 128, 16);

  nom = gtk_label_new ("");
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed5), nom, 136, 40);
  gtk_widget_set_size_request (nom, 128, 16);

  prenom = gtk_label_new ("");
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed5), prenom, 120, 64);
  gtk_widget_set_size_request (prenom, 136, 17);

  label19 = gtk_label_new (_("CIN:"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed5), label19, 16, 88);
  gtk_widget_set_size_request (label19, 88, 17);

  tel = gtk_label_new ("");
  gtk_widget_show (tel);
  gtk_fixed_put (GTK_FIXED (fixed5), tel, 184, 112);
  gtk_widget_set_size_request (tel, 88, 16);

  cin = gtk_label_new ("");
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed5), cin, 104, 88);
  gtk_widget_set_size_request (cin, 88, 16);

  label23 = gtk_label_new (_("Prix final:"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed5), label23, 48, 264);
  gtk_widget_set_size_request (label23, 176, 25);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, button7, "button7");
  GLADE_HOOKUP_OBJECT (window5, prix, "prix");
  GLADE_HOOKUP_OBJECT (window5, label59, "label59");
  GLADE_HOOKUP_OBJECT (window5, date_retour, "date_retour");
  GLADE_HOOKUP_OBJECT (window5, label22, "label22");
  GLADE_HOOKUP_OBJECT (window5, datealler, "datealler");
  GLADE_HOOKUP_OBJECT (window5, label21, "label21");
  GLADE_HOOKUP_OBJECT (window5, typereservation, "typereservation");
  GLADE_HOOKUP_OBJECT (window5, date, "date");
  GLADE_HOOKUP_OBJECT (window5, label20, "label20");
  GLADE_HOOKUP_OBJECT (window5, label18, "label18");
  GLADE_HOOKUP_OBJECT (window5, label53, "label53");
  GLADE_HOOKUP_OBJECT (window5, label17, "label17");
  GLADE_HOOKUP_OBJECT (window5, nom, "nom");
  GLADE_HOOKUP_OBJECT (window5, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (window5, label19, "label19");
  GLADE_HOOKUP_OBJECT (window5, tel, "tel");
  GLADE_HOOKUP_OBJECT (window5, cin, "cin");
  GLADE_HOOKUP_OBJECT (window5, label23, "label23");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed6;
  GtkWidget *treeview1;
  GtkWidget *modif;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label38;
  GtkWidget *Supprimer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label39;
  GtkWidget *ajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label40;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));
  gtk_window_set_position (GTK_WINDOW (window6), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window6), 4, 4);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window6), fixed6);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview1, 264, 0);
  gtk_widget_set_size_request (treeview1, 500, 300);

  modif = gtk_button_new ();
  gtk_widget_show (modif);
  gtk_fixed_put (GTK_FIXED (fixed6), modif, 40, 248);
  gtk_widget_set_size_request (modif, 120, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modif), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox2), label38, FALSE, FALSE, 0);

  Supprimer = gtk_button_new ();
  gtk_widget_show (Supprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), Supprimer, 40, 192);
  gtk_widget_set_size_request (Supprimer, 120, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (Supprimer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox3), label39, FALSE, FALSE, 0);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed6), ajouter, 40, 144);
  gtk_widget_set_size_request (ajouter, 120, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox4), label40, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) modif, "clicked",
                    G_CALLBACK (on_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) Supprimer, "clicked",
                    G_CALLBACK (on_Supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window6, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window6, modif, "modif");
  GLADE_HOOKUP_OBJECT (window6, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window6, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window6, image2, "image2");
  GLADE_HOOKUP_OBJECT (window6, label38, "label38");
  GLADE_HOOKUP_OBJECT (window6, Supprimer, "Supprimer");
  GLADE_HOOKUP_OBJECT (window6, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window6, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window6, image3, "image3");
  GLADE_HOOKUP_OBJECT (window6, label39, "label39");
  GLADE_HOOKUP_OBJECT (window6, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (window6, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window6, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window6, image4, "image4");
  GLADE_HOOKUP_OBJECT (window6, label40, "label40");

  return window6;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed7;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *label27;
  GtkWidget *label26;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label29;
  GtkWidget *labelresultat;
  GtkWidget *entry11;
  GtkWidget *button8;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label28;
  GtkWidget *button9;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("window7"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window7), fixed7);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed7), entry7, 112, 72);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed7), entry8, 112, 120);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed7), entry9, 112, 168);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed7), entry10, 112, 216);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label27 = gtk_label_new (_("prix"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed7), label27, 48, 216);
  gtk_widget_set_size_request (label27, 56, 24);

  label26 = gtk_label_new (_("couleur"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed7), label26, 40, 168);
  gtk_widget_set_size_request (label26, 72, 24);

  label24 = gtk_label_new (_("Model"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed7), label24, 48, 72);
  gtk_widget_set_size_request (label24, 48, 24);

  label25 = gtk_label_new (_("serie"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed7), label25, 48, 120);
  gtk_widget_set_size_request (label25, 48, 24);

  label29 = gtk_label_new (_("date"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed7), label29, 48, 24);
  gtk_widget_set_size_request (label29, 48, 25);

  labelresultat = gtk_label_new ("");
  gtk_widget_show (labelresultat);
  gtk_fixed_put (GTK_FIXED (fixed7), labelresultat, 8, 256);
  gtk_widget_set_size_request (labelresultat, 200, 24);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed7), entry11, 112, 24);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed7), button8, 216, 256);
  gtk_widget_set_size_request (button8, 96, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button8), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox1), label28, FALSE, FALSE, 0);

  button9 = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed7), button9, 320, 256);
  gtk_widget_set_size_request (button9, 96, 32);

  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window7, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window7, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window7, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window7, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window7, label27, "label27");
  GLADE_HOOKUP_OBJECT (window7, label26, "label26");
  GLADE_HOOKUP_OBJECT (window7, label24, "label24");
  GLADE_HOOKUP_OBJECT (window7, label25, "label25");
  GLADE_HOOKUP_OBJECT (window7, label29, "label29");
  GLADE_HOOKUP_OBJECT (window7, labelresultat, "labelresultat");
  GLADE_HOOKUP_OBJECT (window7, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (window7, button8, "button8");
  GLADE_HOOKUP_OBJECT (window7, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window7, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window7, image1, "image1");
  GLADE_HOOKUP_OBJECT (window7, label28, "label28");
  GLADE_HOOKUP_OBJECT (window7, button9, "button9");

  return window7;
}

GtkWidget*
create_window8 (void)
{
  GtkWidget *window8;
  GtkWidget *fixed8;
  GtkWidget *cin;
  GtkWidget *nom;
  GtkWidget *label42;
  GtkWidget *label41;
  GtkWidget *label43;
  GtkWidget *prenom;
  GtkWidget *label44;
  GtkWidget *tel;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *add_fact;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label48;
  GtkWidget *button10;
  GtkWidget *datealler;
  GtkWidget *dateroutour;
  GtkWidget *comboboxentry1;

  window8 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8), _("window8"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window8), fixed8);

  cin = gtk_entry_new ();
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed8), cin, 144, 32);
  gtk_widget_set_size_request (cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin), 8226);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed8), nom, 144, 80);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  label42 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed8), label42, 24, 80);
  gtk_widget_set_size_request (label42, 64, 32);

  label41 = gtk_label_new (_("CIN :"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed8), label41, 16, 32);
  gtk_widget_set_size_request (label41, 72, 32);

  label43 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed8), label43, 32, 128);
  gtk_widget_set_size_request (label43, 64, 24);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed8), prenom, 144, 128);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  label44 = gtk_label_new (_("Tel :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed8), label44, 24, 168);
  gtk_widget_set_size_request (label44, 48, 24);

  tel = gtk_entry_new ();
  gtk_widget_show (tel);
  gtk_fixed_put (GTK_FIXED (fixed8), tel, 144, 168);
  gtk_widget_set_size_request (tel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tel), 8226);

  label45 = gtk_label_new (_("Reservation :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed8), label45, 24, 208);
  gtk_widget_set_size_request (label45, 88, 24);

  label46 = gtk_label_new (_("Date aller :"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed8), label46, 24, 256);
  gtk_widget_set_size_request (label46, 72, 24);

  label47 = gtk_label_new (_("Date retour:"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed8), label47, 16, 296);
  gtk_widget_set_size_request (label47, 96, 25);

  add_fact = gtk_button_new ();
  gtk_widget_show (add_fact);
  gtk_fixed_put (GTK_FIXED (fixed8), add_fact, 176, 352);
  gtk_widget_set_size_request (add_fact, 96, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (add_fact), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox5), label48, FALSE, FALSE, 0);

  button10 = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed8), button10, 288, 352);
  gtk_widget_set_size_request (button10, 98, 37);

  datealler = gtk_entry_new ();
  gtk_widget_show (datealler);
  gtk_fixed_put (GTK_FIXED (fixed8), datealler, 144, 256);
  gtk_widget_set_size_request (datealler, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (datealler), 8226);

  dateroutour = gtk_entry_new ();
  gtk_widget_show (dateroutour);
  gtk_fixed_put (GTK_FIXED (fixed8), dateroutour, 144, 296);
  gtk_widget_set_size_request (dateroutour, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (dateroutour), 8226);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry1, 144, 208);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Vol"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Hotel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Voiture"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Exursion"));

  g_signal_connect ((gpointer) add_fact, "clicked",
                    G_CALLBACK (on_add_fact_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8, window8, "window8");
  GLADE_HOOKUP_OBJECT (window8, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window8, cin, "cin");
  GLADE_HOOKUP_OBJECT (window8, nom, "nom");
  GLADE_HOOKUP_OBJECT (window8, label42, "label42");
  GLADE_HOOKUP_OBJECT (window8, label41, "label41");
  GLADE_HOOKUP_OBJECT (window8, label43, "label43");
  GLADE_HOOKUP_OBJECT (window8, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (window8, label44, "label44");
  GLADE_HOOKUP_OBJECT (window8, tel, "tel");
  GLADE_HOOKUP_OBJECT (window8, label45, "label45");
  GLADE_HOOKUP_OBJECT (window8, label46, "label46");
  GLADE_HOOKUP_OBJECT (window8, label47, "label47");
  GLADE_HOOKUP_OBJECT (window8, add_fact, "add_fact");
  GLADE_HOOKUP_OBJECT (window8, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window8, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window8, image5, "image5");
  GLADE_HOOKUP_OBJECT (window8, label48, "label48");
  GLADE_HOOKUP_OBJECT (window8, button10, "button10");
  GLADE_HOOKUP_OBJECT (window8, datealler, "datealler");
  GLADE_HOOKUP_OBJECT (window8, dateroutour, "dateroutour");
  GLADE_HOOKUP_OBJECT (window8, comboboxentry1, "comboboxentry1");

  return window8;
}

GtkWidget*
create_window9 (void)
{
  GtkWidget *window9;
  GtkWidget *fixed9;
  GtkWidget *label49;
  GtkWidget *datealler;
  GtkWidget *label50;
  GtkWidget *entry14;

  window9 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window9), _("window9"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window9), fixed9);

  label49 = gtk_label_new (_("date aller"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed9), label49, 40, 32);
  gtk_widget_set_size_request (label49, 72, 32);

  datealler = gtk_entry_new ();
  gtk_widget_show (datealler);
  gtk_fixed_put (GTK_FIXED (fixed9), datealler, 144, 32);
  gtk_widget_set_size_request (datealler, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (datealler), 8226);

  label50 = gtk_label_new (_("nom"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed9), label50, 56, 104);
  gtk_widget_set_size_request (label50, 49, 17);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed9), entry14, 152, 96);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window9, window9, "window9");
  GLADE_HOOKUP_OBJECT (window9, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window9, label49, "label49");
  GLADE_HOOKUP_OBJECT (window9, datealler, "datealler");
  GLADE_HOOKUP_OBJECT (window9, label50, "label50");
  GLADE_HOOKUP_OBJECT (window9, entry14, "entry14");

  return window9;
}

